spring:
  application:
    name: USER-SERVICE
  cloud:
    discovery:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true


server:
  port: 4000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    instance-info-replication-interval-seconds: 5


